apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: manage
    port: 15672
    targetPort: 15672
    nodePort: 30000
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30001
